version: '3.3'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    build:
      args:
        RUNNING_ENV: prod
  mongodb:
    ports:
      - 27017
    volumes:
      - ./_data/db:/data/db
  gateway:
    environment:
      - NODE_ENV=production
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-gateway && npm run build && npm run prod"
  cache:
    environment:
      - NODE_ENV=production
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-cache && npm run build && npm run prod"
  event:
    environment:
      - NODE_ENV=production
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-event && npm run build && npm run prod"
  notify:
    environment:
      - NODE_ENV=production
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-notify && npm run build && npm run prod"
  user:
    environment:
      - NODE_ENV=production
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-user && npm run build && npm run prod"
  comment:
    environment:
      - NODE_ENV=production
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-comment && npm run build && npm run prod"
    volumes:
      - /usr/src/app/server-comment/node_modules
  client:
    environment:
      - NODE_ENV=production
    command: npm run build-prod
  